name: Run Autograding Checks

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Espresso Tests
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run unit tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
